[package]
name = "devdash"
version = "0.1.4"
description = "DevDash: your team's space on your own server"
license = "MIT"
edition = "2021"

[lib]
name = "devdash_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5", features = [] }

[dependencies]
tauri = { version = "2.12", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-notification = "2"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true
